/*script generated for free with OnlineDataGenerator available at: https://www.onlinedatagenerator.com */
CREATE TABLE MOCKDATA(ID BIGINT,JobTitle VARCHAR(500),EmailAddress VARCHAR(500),FirstNameLastName VARCHAR(500));

INSERT INTO MOCKDATA VALUES('1','Health Educator','Miley_May1984@mafthy.com','Miley May');
INSERT INTO MOCKDATA VALUES('2','Cashier','Chad_Plumb2760@bretoux.com','Chad Plumb');
INSERT INTO MOCKDATA VALUES('3','Bellman','Mina_Emmott9763@dionrab.com','Mina Emmott');
INSERT INTO MOCKDATA VALUES('4','HR Coordinator','Martin_Oakley6869@famism.biz','Martin Oakley');
INSERT INTO MOCKDATA VALUES('5','Health Educator','Cedrick_Speed9920@grannar.com','Cedrick Speed');
INSERT INTO MOCKDATA VALUES('6','Audiologist','Sebastian_Dobson2728@gmail.com','Sebastian Dobson');
INSERT INTO MOCKDATA VALUES('7','CNC Operator','Domenic_Wood4124@grannar.com','Domenic Wood');
INSERT INTO MOCKDATA VALUES('8','Baker','Johnny_Young3175@jiman.org','Johnny Young');
INSERT INTO MOCKDATA VALUES('9','Health Educator','Gil_Thatcher7454@bretoux.com','Gil Thatcher');
INSERT INTO MOCKDATA VALUES('10','IT Support Staff','Samantha_Chadwick4640@naiker.biz','Samantha Chadwick');
INSERT INTO MOCKDATA VALUES('11','Investment  Advisor','Johnny_Needham5644@hourpy.biz','Johnny Needham');
INSERT INTO MOCKDATA VALUES('12','Dentist','Angelina_Benson4007@extex.org','Angelina Benson');
INSERT INTO MOCKDATA VALUES('13','Insurance Broker','Chris_Kirby5296@bretoux.com','Chris Kirby');
INSERT INTO MOCKDATA VALUES('14','Operator','Roger_Kelly6048@mafthy.com','Roger Kelly');
INSERT INTO MOCKDATA VALUES('15','Auditor','Chanelle_Wooldridge8480@typill.biz','Chanelle Wooldridge');
INSERT INTO MOCKDATA VALUES('16','Service Supervisor','Clint_Fenton9525@atink.com','Clint Fenton');
INSERT INTO MOCKDATA VALUES('17','Design Engineer','Erick_Owen4492@eirey.tech','Erick Owen');
INSERT INTO MOCKDATA VALUES('18','Inspector','Ronald_Latham1611@extex.org','Ronald Latham');
INSERT INTO MOCKDATA VALUES('19','HR Specialist','Emma_Robinson2912@iatim.tech','Emma Robinson');
INSERT INTO MOCKDATA VALUES('20','Pharmacist','Phillip_Upsdell3921@nickia.com','Phillip Upsdell');
INSERT INTO MOCKDATA VALUES('21','Laboratory Technician','Vanessa_Brooks3624@womeona.net','Vanessa Brooks');
INSERT INTO MOCKDATA VALUES('22','Steward','Sienna_Middleton8625@tonsy.org','Sienna Middleton');
INSERT INTO MOCKDATA VALUES('23','Doctor','Nathan_Broomfield1052@muall.tech','Nathan Broomfield');
INSERT INTO MOCKDATA VALUES('24','Chef Manager','Boris_Sherwood988@qater.org','Boris Sherwood');
INSERT INTO MOCKDATA VALUES('25','Associate Professor','Keira_Hood8960@guentu.biz','Keira Hood');
INSERT INTO MOCKDATA VALUES('26','Staffing Consultant','Tom_Rainford3634@ubusive.com','Tom Rainford');
INSERT INTO MOCKDATA VALUES('27','Lecturer','Willow_Ellison5920@dionrab.com','Willow Ellison');
INSERT INTO MOCKDATA VALUES('28','Webmaster','Bridget_Thorne8990@famism.biz','Bridget Thorne');
INSERT INTO MOCKDATA VALUES('29','Service Supervisor','Carolyn_Dann1455@infotech44.tech','Carolyn Dann');
INSERT INTO MOCKDATA VALUES('30','Chef Manager','Gabriel_Ranks344@twace.org','Gabriel Ranks');
INSERT INTO MOCKDATA VALUES('31','Lecturer','Hank_Camden8238@gmail.com','Hank Camden');
INSERT INTO MOCKDATA VALUES('32','Front Desk Coordinator','Hayden_Russell8311@cispeto.com','Hayden Russell');
INSERT INTO MOCKDATA VALUES('33','Laboratory Technician','Susan_Wilde5382@mafthy.com','Susan Wilde');
INSERT INTO MOCKDATA VALUES('34','Restaurant Manager','Nate_Rogers6573@yahoo.com','Nate Rogers');
INSERT INTO MOCKDATA VALUES('35','Webmaster','Erin_Simpson2184@ovock.tech','Erin Simpson');
INSERT INTO MOCKDATA VALUES('36','Biologist','George_John4980@fuliss.net','George John');
INSERT INTO MOCKDATA VALUES('37','Investment  Advisor','Julius_Rehman4947@womeona.net','Julius Rehman');
INSERT INTO MOCKDATA VALUES('38','Designer','Gabriel_Wills9516@yahoo.com','Gabriel Wills');
INSERT INTO MOCKDATA VALUES('39','Investment  Advisor','Kirsten_Shields6826@zorer.org','Kirsten Shields');
INSERT INTO MOCKDATA VALUES('40','IT Support Staff','Jade_Burge9792@ubusive.com','Jade Burge');
INSERT INTO MOCKDATA VALUES('41','Investment  Advisor','Marvin_Uddin7545@tonsy.org','Marvin Uddin');
INSERT INTO MOCKDATA VALUES('42','Clerk','Miriam_Gordon7769@jiman.org','Miriam Gordon');
INSERT INTO MOCKDATA VALUES('43','Loan Officer','Marla_Salt3251@corti.com','Marla Salt');
INSERT INTO MOCKDATA VALUES('44','Staffing Consultant','Angelica_Edwards8489@ovock.tech','Angelica Edwards');
INSERT INTO MOCKDATA VALUES('45','Paramedic','Tom_Wright6961@famism.biz','Tom Wright');
INSERT INTO MOCKDATA VALUES('46','Global Logistics Supervisor','Jayden_Cox7499@liret.org','Jayden Cox');
INSERT INTO MOCKDATA VALUES('47','Investment  Advisor','Chelsea_Gordon4864@gmail.com','Chelsea Gordon');
INSERT INTO MOCKDATA VALUES('48','Cashier','Jamie_Varley5145@bauros.biz','Jamie Varley');
INSERT INTO MOCKDATA VALUES('49','CNC Operator','Sage_Clarkson1353@corti.com','Sage Clarkson');
INSERT INTO MOCKDATA VALUES('50','Executive Director','Phoebe_Nicholls8624@zorer.org','Phoebe Nicholls');

